import { jsPDF } from "jspdf";
import { toExportMarkdown } from "./engine/response-normalizer";
import type { ResearchResult } from "./engine/types";

/**
 * Generates a PDF from a ResearchResult using jsPDF.
 * Since we don't have a full HTML-to-PDF renderer easily available in this environment,
 * we'll create a well-formatted text-based PDF or use a hidden DOM element with html2canvas/jspdf.
 * 
 * For simplicity and reliability in this setup, we'll use a high-quality text-based approach
 * that mimics the report structure.
 */
export async function exportToPdf(result: ResearchResult) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;

  let y = 25;

  // Helper to add text with wrapping
  const addText = (text: string, size: number = 10, isBold: boolean = false, color: [number, number, number] = [0, 0, 0]) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.setTextColor(color[0], color[1], color[2]);
    
    const lines = doc.splitTextToSize(text, contentWidth);
    
    // Check for page break
    if (y + lines.length * (size / 2) > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
    
    doc.text(lines, margin, y);
    y += lines.length * (size / 2.5) + 4;
  };

  const addHeading = (text: string, level: number = 1) => {
    const size = level === 1 ? 18 : level === 2 ? 14 : 12;
    y += 4;
    addText(text.toUpperCase(), size, true, [0, 0, 0]);
    y += 2;
  };

  // ── Header ───────────────────────────────────────────────────
  doc.setFillColor(12, 12, 12);
  doc.rect(0, 0, pageWidth, 40, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("RESEARCH REPORT", margin, 20);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated by ResAgent on ${new Date().toLocaleDateString()}`, margin, 30);
  
  y = 55;

  // ── Overview ─────────────────────────────────────────────────
  if (result.overview) {
    addHeading("Overview", 1);
    addText(result.overview.replace(/###/g, "").replace(/\*\*/g, ""), 10);
  }

  // ── Key Insights ─────────────────────────────────────────────
  if (result.keyInsights.length > 0) {
    addHeading("Key Insights", 1);
    result.keyInsights.forEach((insight) => {
      addText(`• ${insight.replace(/\*\*/g, "")}`, 10);
    });
  }

  // ── Details ──────────────────────────────────────────────────
  if (result.details) {
    addHeading("In-Depth Analysis", 1);
    // Split by chapters if present
    const chapters = result.details.split(/###/);
    chapters.forEach(chapter => {
      if (!chapter.trim()) return;
      const lines = chapter.trim().split("\n");
      const title = lines[0].trim();
      const body = lines.slice(1).join("\n").trim();
      
      if (title) addText(title, 12, true);
      if (body) addText(body.replace(/\*\*/g, ""), 10);
      y += 4;
    });
  }

  // ── Comparison ───────────────────────────────────────────────
  if (result.comparison) {
    addHeading("Comparative Assessment", 1);
    addText(result.comparison.replace(/###/g, "").replace(/\*\*/g, ""), 10);
  }

  // ── Conclusion ───────────────────────────────────────────────
  if (result.conclusion) {
    addHeading("Conclusion & Recommendations", 1);
    addText(result.conclusion.replace(/###/g, "").replace(/\*\*/g, ""), 10);
  }

  // ── Sources ──────────────────────────────────────────────────
  if (result.sources.length > 0) {
    addHeading("Sources & References", 1);
    result.sources.forEach((source, i) => {
      addText(`[${i + 1}] ${source.title}`, 10, true);
      addText(`URL: ${source.url}`, 8, false, [100, 100, 100]);
      y += 2;
    });
  }

  // ── Footer ───────────────────────────────────────────────────
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by ResAgent | Model: ${result.metadata.model}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
  }

  // ── Download ─────────────────────────────────────────────────
  doc.save(`ResAgent-Research-${Date.now()}.pdf`);
}
